### ISSUE TITLE
미쳤습니까, 휴먼?

### ISSUE THREAD

**Issue by ghkdxofla** [rurumimic/todo-list#1]
# Issues
- 과도한 커밋을 통한 불법 녹지화
- 커밋 메시지가 충격적임(eg. 1, 2, qwer...)

**감사합니다**

**Comment by rurumimic** [comment]
귀하의 문제를 이해할 수 없습니다.
이 문제는 종료됩니다.

---

![](https://cdn.pixabay.com/photo/2020/10/15/18/16/cannabis-5657625_1280.jpg)

---

thanks
